[package]
name = "my-rust-bin"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
v1 = []
v2 = []

[[bin]]
name = "my-rust-bin"
path = "src/main.rs"
